export const WISH_ADD_ITEM = 'WISH_ADD_ITEM';
export const WISH_ADD_ITEM_FAIL = 'WISH_ADD_ITEM_FAIL';
export const WISH_EMPTY = 'WISH_EMPTY';
export const WISH_REMOVE_ITEM = 'WISH_REMOVE_ITEM';
export const WISH_SAVE_SHIPPING_ADDRESS = 'WISH_SAVE_SHIPPING_ADDRESS';
export const WISH_SAVE_PAYMENT_METHOD = 'WISH_SAVE_PAYMENT_METHOD';
