export const WISH_ADD_ITEM = 'WISH_ADD_ITEM';
export const WISH_ADD_ITEM_FAIL = 'WISH_ADD_ITEM_FAIL';
export const WISH_EMPTY = 'WISH_EMPTY';
export const WISH_REMOVE_ITEM = 'WISH_REMOVE_ITEM';
export const WISH_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const WISH_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const WISH_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

